### ISSUE TITLE
where's the pymux repo gone?

### ISSUE THREAD

**Issue by rofl0r** [jonathanslenders/libpymux#3]
also all image links on https://pypi.org/project/pymux/ are dead

**Comment by jonathanslenders** [comment]
I'm sorry, I transferred the repository to https://github.com/prompt-toolkit/pymux, but the organization got flagged right after moving everything. I contacted GitHub to restore access.

**Comment by rofl0r** [comment]
cool. could you ping me when it's available? thanks!

**Comment by jonathanslenders** [comment]
It's back!
